version: '3.8'

volumes:
  mongo_data:
  mongo:
    image: mongo:6.0
    restart: unless-stopped
    environment:
      MONGO_USERNAME: root
      MONGO_PASSWORD: 12345
      MONGO_DATABASE: users
    volumes:
      - ./mongo_data:/data/db
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
      mongo:
        condition: service_healthy
    restart: unless-stopped
    environment:
      - LISTEN_PORT=:8889
      - MONGO_URI=mongodb://root:12345@mongo:27017/users?authSource=admin
    volumes:
      - ./.local:/local
    ports:
      - "8889:8889"
